---
name: HTTP-BrowserDetect
version: 1.02
author:
  - 'Olaf Alders <olaf@wundercounter.com>'
abstract: Determine the Web browser, version, and platform from an HTTP user agent string
license: perl
build_requires:
  Data::Dump: 0
  Exporter: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  HTTP::BrowserDetect:
    file: lib/HTTP/BrowserDetect.pm
    version: 1.02
resources:
  license: http://dev.perl.org/licenses/
