---
abstract: 'Determine Web browser, version, and platform from an HTTP user agent string'
author:
  - 'Lee Semel <lee@semel.net>'
  - 'Peter Walsham'
  - 'Olaf Alders <olaf@wundercounter.com> (current maintainer)'
build_requires:
  FindBin: '0'
  JSON::PP: '0'
  Module::Build: '0.28'
  Path::Tiny: '0'
  Test::FailWarnings: '0'
  Test::More: '0'
  Test::Most: '0'
  Test::NoWarnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-BrowserDetect
requires:
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: http://github.com/oalders/HTTP-BrowserDetect/issues
  homepage: https://metacpan.org/release/HTTP-BrowserDetect
  repository: https://github.com/oalders/http-browserdetect.git
version: '1.74'
x_contributors:
  - 'Aran Deltac <bluefeet@gmail.com>'
  - 'David Ihnen <davidihnen@gmail.com>'
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
  - 'Graham Barr <gbarr@pobox.com>'
  - 'Hao Wu <hwu@intellisurvey.com>'
  - 'Jon Jensen <jon@endpoint.com>'
  - 'Maros Kollar <maros@k-1.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Olivier Bilodeau <olivier@bottomlesspit.org>'
  - 'Paul Findlay <paul@findlay.net.nz>'
  - 'Perlover <perlover@perlover.com>'
  - 'Robin Smidsrød <robin@smidsrod.no>'
  - 'Ronald J Kimball <rkimball@pangeamedia.com>'
  - 'Surikov Alexey <surikov@alexey-pc.kiteventures.local>'
  - 'Thom Blake <thom@odonnellpdc.com>'
  - 'Uwe <uwe@uwevoelker.de>'
  - 'cho45 <cho45@lowreal.net>'
  - 'joatis <joatis3@gmail.com>'
  - 'ktat <ktat.is@gmail.com>'
  - 'lsaunders <lsaunders@dev05.backbone.i5invest.com>'
  - 'vti <viacheslav.t@gmail.com>'
  - 'yeahoffline <frank.gasser@gmail.com>'
