---
name: HTTP-BrowserDetect
version: 1.08
author:
  - 'Olaf Alders <olaf@wundercounter.com>'
abstract: Determine Web browser, version, and platform from an HTTP user agent string
license: perl
build_requires:
  Data::Dump: 0
  Exporter: 0
  FindBin: 0
  Test::More: 0
  YAML::Tiny: 0
configure_requires:
  Module::Build: 0.35
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  HTTP::BrowserDetect:
    file: lib/HTTP/BrowserDetect.pm
    version: 1.08
resources:
  license: http://dev.perl.org/licenses/
