---
abstract: 'Determine Web browser, version, and platform from an HTTP user agent string'
author:
  - 'Olaf Alders <olaf@wundercounter.com> (current maintainer)'
build_requires:
  Data::Dump: 0
  English: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0
  YAML::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-BrowserDetect
requires:
  Exporter: 0
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTTP-BrowserDetect
  repository: http://github.com/oalders/http-browserdetect
version: 1.14
