---
abstract: 'Determine Web browser, version, and platform from an HTTP user agent string'
author:
  - 'Olaf Alders <olaf@wundercounter.com>'
build_requires:
  Data::Dump: 0
  Exporter: 0
  FindBin: 0
  Test::More: 0
  YAML::Tiny: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-BrowserDetect
provides:
  HTTP::BrowserDetect:
    file: lib/HTTP/BrowserDetect.pm
    version: 1.11
resources:
  license: http://dev.perl.org/licenses/
version: 1.11
